version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_data:/var/lib/postgresql/database/

  test_db:
    image: postgres:latest
    container_name: test_database

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_postgres

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && uvicorn --factory src.main:create_app --host 0.0.0.0 --port 8000"
    restart: always
    volumes:
      - .:/usr/src/project
    container_name: fastapi
    depends_on:
      - db
      -   test_db
    ports:
      - "8000:8000"

volumes:
  database_data:
